- hosts: all
  
  tasks:
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia


    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx
        - unzip
   
    - name: "unzip do bootstrap"
      become: true
      shell: "wget https://github.com/startbootstrap/startbootstrap-agency/archive/gh-pages.zip -y"
      shell: "unzip gh-pages.zip -y"
      shell: "mv startbootstrap-agency-gh-pages /var/www/site -y"
     
    - name: "altera arquivo nginx"
      become: yes
      replace:
        path: '/etc/nginx/sites-available/default'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'root /var/www/default', value: 'root /var/www/site' }
      
    - name: "restart do nginx"
      become: true
      shell: "systemctl restart nginx -y"
      

    - shell: cat /var/www/wordpress/wp-config.php
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "

    