# ### dar nome para o master
# ssh -i ~/Desktop/devops/treinamentoItau ubuntu@ec2-54-226-188-130.compute-1.amazonaws.com

# sudo su -
# hostname k8s-master 
# echo "k8s-master" > /etc/hostname
# bash

# sudo su -
# hostname k8s-node-0
# echo "k8s-node-0" > /etc/hostname
# bash

# sudo su -
# hostname k8s-node-1
# echo "k8s-node-1" > /etc/hostname
# bash

# sudo su -
# hostname k8s-node-2
# echo "k8s-node-2" > /etc/hostname
# bash


- hosts: ec2-k8s-master
  tasks:
      
    - name: "Alterando nome da maquina"
      shell: sudo hostname k8s-master && sudo echo "k8s-master" > /etc/hostname  
      become: yes

- hosts: ec2-k8s-worker1
  tasks:
      
    - name: "Alterando nome da maquina worker 0"
      shell: sudo hostname k8s-worker0 && sudo echo "k8s-worker0" > /etc/hostname 
      become: yes

- hosts: ec2-k8s-worker2
  tasks:
      
    - name: "Alterando nome da maquina worker 2"
      shell: sudo hostname k8s-worker1 && sudo echo "k8s-worker1" > /etc/hostname 
      become: yes

- hosts: ec2-k8s-worker3
  tasks:
      
    - name: "Alterando nome da maquina worker 3"
      shell: sudo hostname k8s-worker2 && sudo echo "k8s-worker2" > /etc/hostname 
      become: yes
    
  



